### ISSUE TITLE
ライセンスについて

### ISSUE THREAD

**Issue by mtripg6666tdr** [kinoko2k/Punishment-Program#1]
TL;DR
無断で二次配布してはいけないものにGPLライセンスは使用できないと思われます、、
Ref. [正しく知れば怖くない GPL ライセンスの特徴 | yamory Blog](https://yamory.io/blog/about-gpl-license/#:~:text=%E8%91%97%E4%BD%9C%E7%89%A9%E3%81%AE%E8%87%AA%E7%94%B1%E3%81%AA%E5%88%A9%E7%94%A8%E3%83%BB%E6%94%B9%E5%A4%89%E3%83%BB%E5%86%8D%E9%85%8D%E5%B8%83%E3%81%99%E3%82%8B%E6%A8%A9%E5%88%A9%E3%82%92%E4%BA%BA%E3%80%85%E3%81%AB%E6%8F%90%E4%BE%9B%E3%81%97%E3%80%81%E3%81%9D%E3%81%93%E3%81%8B%E3%82%89%E6%B4%BE%E7%94%9F%E3%81%97%E3%81%9F%E8%91%97%E4%BD%9C%E7%89%A9%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6%E3%82%82%E3%81%93%E3%82%8C%E3%82%89%E3%81%AE%E8%A1%8C%E7%82%BA%E3%82%92%E5%88%B6%E9%99%90%E3%81%97%E3%81%A6%E3%81%AF%E3%81%AA%E3%82%89%E3%81%AA%E3%81%84%E3%81%A8%E3%81%99%E3%82%8B%E8%80%83%E3%81%88)

**Comment by kinoko2k** [comment]
確かに...

**Comment by kinoko2k** [comment]
bsdに直して、使う場合は載せる形にしました。
